Repository bellshade/Golang, pull requests merged in 2023-03, with the labels that each got.

#32 docs: menambah go syntax hightlight ke block code
  basic/03_variabel/README.md
  basic/04_constant/README.md
  basic/09_string/README.md
  basic/19_error_handling/DEFER.md
  basic/19_error_handling/README.md
  intermediate/concurrency/goroutines/README.md
  intermediate/generic/README.md
Labels: ready-to-merge, markdown files

#29 tambah penjelasan tentang pass by reference & pointer receiver
  basic/11_pointer/README.md
  basic/11_pointer/pointer.go
Labels: markdown files, Golang files

#33 fix: test memperbaiki unitesting
  .github/workflows/golang_test.yml
  .golangci.yml
  go.mod
  math/cos.go
  math/cos_test.go
  math/doc.go
  math/math_test.go
  math/sin.go
  math/sin_test.go
  math_implementation/logaritma/logaritma.go
  math_implementation/logaritma/logaritma_test.go
Labels: Golang files
