Repository bellshade/Golang, pull requests merged in 2025-07, with the labels that each got.

#47 chore: menambahkan makefile
  .github/workflows/golang_test.yml
  Makefile
Labels: ready-to-merge

#48 chore: menambahkan tipe data byte
  intermediate/tipe_data/06_byte/README.md
  intermediate/tipe_data/06_byte/contoh_byte.go
Labels: ready-to-merge, markdown files, Golang files

#50 chore: upgrade Go version to 1.24.3
  go.mod
Labels: ready-to-merge

#51 Tests
  .golangci.yml
  Makefile
  math/prima/cek_prima.go
  math_implementation/armstrong/is_armstrong.go
  searching/interpolation.go
  searching/linear_searching.go
  searching/ternary_searching.go
  tests/algorithm/searching/interpolation_test.go
  tests/algorithm/searching/linear_searching_test.go
  tests/algorithm/searching/ternary_searching_test.go
  tests/algorithm/searching/test_data_search.go
  tests/math/cek_prima_test.go
  tests/math/cos_test.go
  tests/math/implementation/faktorial_test.go
  tests/math/implementation/is_armstrong_test.go
  tests/math/implementation/logaritma_test.go
  tests/math/sin_test.go
  tests/test_utils.go
Labels: Ok to merge, ready-to-merge, Golang files

#52 chore: tambahkan workflow untuk pengujian di windows
  .github/workflows/golang_test.yml
Labels: ready-to-merge

#53 docs: update pull request template untuk proyek Golang
  .github/pull_request_template.md
Labels: ready-to-merge, markdown files

#55 chore: menghapus funding bellshade
  .github/FUNDING.yml
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  basic/01_introduction/README.md
  basic/05_operator/README.md
  basic/06_looping/README.md
  basic/07_fungsi/README.md
  basic/08_scope/README.md
  basic/10_array/README.md
  basic/10_array/SLICE.md
  basic/12_structure/README.md
  basic/16_rekursif/README.md
  basic/18_interface/README.md
  basic/19_error_handling/DEFER.md
  basic/19_error_handling/PANIC.md
  basic/19_error_handling/README.md
Labels: ready-to-merge, markdown files

#56 refactor: ganti nama variabel digit_kanan menjadi digitKanan agar konsisten
  math_implementation/armstrong/is_armstrong.go
Labels: ready-to-merge, Golang files

#59 chore: menambahkan penjelasan tentang embed package
  utilities/embed/README.md
  utilities/embed/embed.go
  utilities/embed/folder/file1.hash
  utilities/embed/folder/file2.hash
  utilities/embed/folder/single_file.txt
Labels: ready-to-merge, markdown files, Golang files

#61 chore: menambahkan materi database sql
  utilities/database_sql/README.md
  utilities/database_sql/databaseSql.go
Labels: ready-to-merge, markdown files, Golang files

#62 chore: menambahkan penjelasan tentang atomic di golang
  intermediate/concurrency/goroutines/README.md
  intermediate/concurrency/goroutines/contoh_atomic.go
Labels: ready-to-merge, markdown files, Golang files

#63 chore: menambahkan operasi pertambahan matriks
  math/matriks/op_tambah.go
  tests/math/matriks/op_tambah_test.go
Labels: ready-to-merge, Golang files
